### ISSUE TITLE
problem with account's

### ISSUE THREAD

**Issue by ene80** [MeoMunDep/Chill-Guy-Xmas#1]
Can you tell me what i'm doig wrong please.
In datas i set query_id ( then leave a space) and then user_id (using the tool you linked)
i do it for my 3 account's, but when i run the script i start 5 account's and don't complete task on them

**Comment by MeoMunDep** [comment]
no screenshot not solve anything, i cant understand what u say dude.

**Comment by ene80** [comment]
i have 3 accounts: query_id user_id
![image](https://github.com/user-attachments/assets/c7895fb6-e33b-446b-98ec-07be30d0f70c)
the bot start 5 ( what are this 2 more accounts?)
![image](https://github.com/user-attachments/assets/d0656860-c378-4a8a-b7b0-0c459e4bcb0b)
And it's not doing anything on mine account's
![image](https://github.com/user-attachments/assets/9cb86a6e-dacf-407c-8ac2-ba7e9d1bab80)
![image](https://github.com/user-attachments/assets/69bf7079-3fcf-486d-a9bb-91e9b7763fca)

**Comment by MeoMunDep** [comment]
? bruh u not even read the guide, read again and you know why bruh, many people like u, just download script and not even read the guides, pls bro, read again.
